angular.module('sextant.config', [])
  .constant('configuration', {
        "EVENT_SERVICE_URL": "@@EVENT_SERVICE_URL",
        "MINION_SERVICE_URL": "@@MINION_SERVICE_URL",
        "POD_GET_URL": "@@POD_GET_URL",
        "PODS_GET_URL": "@@PODS_GET_URL",
        "POD_DELETE_URL": "@@POD_DELETE_URL",
        "RC_SERVICE_URL": "@@RC_SERVICE_URL",
        "LOADBALANCER_SERVICE_URL": "@@LOADBALANCER_SERVICE_URL",
        "DOCKER_HUB_SEARCH_URL": "@@DOCKER_HUB_SEARCH_URL",
        "DOCKERUI_SERVICE_URL": "@@DOCKERUI_SERVICE_URL",
        "NUMBER_OF_ITEMS_PER_PAGE": "@@NUMBER_OF_ITEMS_PER_PAGE",
        "NUMBER_OF_DISPLAYED_PAGES": "@@NUMBER_OF_DISPLAYED_PAGES",
        "TIMEOUT": "@@TIMEOUT"
    });

